# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EKxjOS6yc57XeEbJDync5F3iMRKbhqqO
"""

from PIL import Image
import matplotlib.pyplot as plt

# Rasm faylining nomi
rasm_fayli = "IMG_20240219_165635_442.jpg"

try:
    # Rasmni ochamiz
    rasm = Image.open(rasm_fayli)

    # Rasmni oq-qora formatga o'tkazamiz
    oq_qora_rasm = rasm.convert("L")

    # Oq-qora rasmni ko'rsatamiz
    plt.imshow(oq_qora_rasm, cmap="gray")
    plt.axis('off')  # O'qlarni o'chirib tashlaymiz
    plt.title("Ronaldo Rasmi (Oq-qora)")
    plt.show()

except FileNotFoundError:
    print(f"{rasm_fayli} fayli topilmadi. Iltimos, fayl yo'lini tekshiring.")
except Exception as e:
    print(f"Rasmni ochishda xatolik yuz berdi: {e}")